#line 2 "lex_sql.cpp"
/*
这里的代码会被复制到lex_sql.cpp的最开始位置
定义yy_size_t的原因是因为flex生成的代码，会使用yy_size_t与其他类型的数字
做比较，导致编译报警
*/
#define YY_TYPEDEF_YY_SIZE_T
typedef int yy_size_t;

/* 参考生成的lex_sql.cpp代码，这个宏定义会放在每次运行yylex()最开始的地方 */
#define YY_USER_INIT                                         \
  yycolumn = 0;

/* 参考生成的lex_sql.cpp代码，这个宏定义会放在解析一个token之后，也可以在网上找到大量的参考资料 */
/* 我们在这里设置当前解析的token的位置信息，这样在yacc中就可以使用这些信息了 */
#define YY_USER_ACTION                                       \
do {                                                         \
  yylloc->first_line   = yylloc->last_line = yylineno;       \
  yylloc->first_column = yycolumn;                           \
  yylloc->last_column  = yylloc->first_column + yyleng - 1;  \
  yycolumn += yyleng;                                        \
}                                                            \
while (0);

#line 26 "lex_sql.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yyget_lval
#define yyget_lval_ALREADY_DEFINED
#else
#define yyget_lval yyget_lval
#endif

#ifdef yyset_lval
#define yyset_lval_ALREADY_DEFINED
#else
#define yyset_lval yyset_lval
#endif

#ifdef yyget_lloc
#define yyget_lloc_ALREADY_DEFINED
#else
#define yyget_lloc yyget_lloc
#endif

#ifdef yyset_lloc
#define yyset_lloc_ALREADY_DEFINED
#else
#define yyset_lloc yyset_lloc
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin , yyscanner )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void yyrestart ( FILE *input_file , yyscan_t yyscanner );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size , yyscan_t yyscanner );
void yy_delete_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yy_flush_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
void yypop_buffer_state ( yyscan_t yyscanner );

static void yyensure_buffer_stack ( yyscan_t yyscanner );
static void yy_load_buffer_state ( yyscan_t yyscanner );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file , yyscan_t yyscanner );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER , yyscanner)

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len , yyscan_t yyscanner );

void *yyalloc ( yy_size_t , yyscan_t yyscanner );
void *yyrealloc ( void *, yy_size_t , yyscan_t yyscanner );
void yyfree ( void * , yyscan_t yyscanner );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(yyscanner) (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state ( yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  , yyscan_t yyscanner);
static int yy_get_next_buffer ( yyscan_t yyscanner );
static void yynoreturn yy_fatal_error ( const char* msg , yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;
#define YY_NUM_RULES 90
#define YY_END_OF_BUFFER 91
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[308] =
    {   0,
        0,    0,    0,    0,   91,   89,    1,    2,   89,   89,
       89,   70,   71,   84,   82,   74,   83,    6,   85,    3,
        5,   79,   75,   81,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   72,   73,   90,   78,    0,
       87,    0,    0,   88,    0,    0,    3,   76,   77,   80,
       69,   69,   69,   55,   69,   69,   54,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   66,   65,   69,   69,   69,   69,   69,   69,   69,
       69,   16,   24,   69,   69,   69,   69,   69,   69,   69,

       69,   69,   69,   69,   69,   69,   69,    0,    0,    4,
       23,   51,   47,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   37,   69,   69,   69,
       69,   45,   46,   58,   69,   69,   69,   69,   30,   69,
       69,   48,   69,   69,   69,   69,   69,   69,   69,   69,
       69,    0,    0,   69,   20,   41,   69,   69,   69,   69,
       38,   69,    9,   11,   69,    7,   69,   69,   69,   21,
       69,   69,    8,   69,   69,   69,   69,   26,   62,   69,
       59,   69,   63,   69,   69,   69,   17,   69,   18,   69,

       39,   69,   69,   69,   69,   15,   69,    0,    0,   31,
       69,   69,   49,   69,   69,   69,   69,   42,   69,   53,
       69,   14,   69,   61,   69,   69,    0,   69,   52,   69,
       69,   69,   12,   69,   69,   69,   69,   22,    0,    0,
       32,   69,   10,   28,   67,   69,   57,   68,   44,   69,
       25,   69,    0,   69,   69,   19,   69,   13,   60,   29,
       27,   40,    0,    0,   69,   50,   69,   69,    0,   69,
       69,   56,    0,    0,    0,    0,   69,   69,   69,    0,
       64,   33,    0,    0,   69,   69,   69,   43,   86,   86,
        0,   86,   86,    0,   69,   69,   69,   69,   69,   34,

       69,   69,   69,   36,   69,   35,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    2,    3,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    1,    1,    1,    7,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   16,   17,
       16,   16,   16,   16,   16,   16,   16,    1,   18,   19,
       20,   21,    1,    1,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   33,   34,   35,   36,   37,
       38,   39,   40,   41,   42,   43,   44,   45,   46,   47,
       48,    1,   49,    1,   50,    1,   51,   52,   53,   54,

       55,   56,   57,   58,   59,   60,   61,   62,   63,   64,
       65,   66,   67,   68,   69,   70,   71,   72,   73,   74,
       75,   47,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[76] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    2,    2,    1,    1,    1,
        1,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    1,    1,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2
    } ;

static const flex_int16_t yy_base[313] =
    {   0,
        0,    0,    0,    0,  231, 1177, 1177, 1177,  207,   70,
       72, 1177, 1177, 1177, 1177, 1177, 1177, 1177, 1177,   64,
     1177,   62, 1177,  197,   68,   74,   76,   80,   78,   97,
      100,  129,  126,  137,   93,  140,  147,  155,  165,  158,
      218,  170,  172,  202,  109, 1177, 1177, 1177, 1177,  177,
     1177,  195,  153, 1177,  223,  105,  199, 1177, 1177, 1177,
        0,  162,  225,  232,  235,  238,  229,  251,  253,  265,
      261,  255,  281,  274,  285,  295,  301,  310,  313,  292,
      321,  368,  303,  331,  108,  325,  336,  346,  354,  351,
      339,  307,  357,  363,  382,  390,  397,  400,  411,  413,

      423,  426,  432,  434,  388,  443,  454,  360,  457,  316,
      437,  460,  462,  465,  467,  471,  473,  476,  483,  486,
      488,  495,  499,  509,  513,  511,  516,  524,  532,  539,
      544,  547,  552,  555,  560,  563,  575,  577,   74,  580,
      583,  585,  588,  600,  603,  605,  609,  607,  611,  613,
      622,  627,  629,  631,  633,  635,  650,  638,  642,  652,
      659,  671,  678,  662,  675,  683,  688,  694,  690,  697,
      699,  703,  705,  707,  716,  718,  720,  723,  729,  732,
      737,  746,  739,  749,  752,  759,  761,  766,  771,   88,
      773,  775,  779,  789,  792,  795,  800,  804,  808,  815,

      817,  819,  821,  823,  829,  826,  834,  197,   94,  836,
      842,  847,  850,  855,  858,  852,  863,  860,  870,  879,
      881,  883,  888,  891,  901,  145,  168,  903,  899,  907,
      911,  916,  914,  919,  930,  932,  943,  934,  947,  950,
      945,  952,  959,  961,  963,  970,  972,  974,  976,  978,
      980,  167,  243,  983,  990,  987,  992,  996, 1003, 1005,
     1007, 1009, 1022, 1020, 1015, 1013, 1025,  252,  318, 1032,
     1034, 1036, 1040,  488, 1054,  273, 1038, 1043,  330,  359,
     1046, 1056, 1068, 1074, 1060, 1082,  378, 1177, 1177,  144,
     1076,  117, 1177, 1082, 1085, 1088,  487, 1093, 1095,    0,

     1097, 1100, 1104, 1106, 1108, 1121, 1177, 1170, 1172, 1174,
      102,   75
    } ;

static const flex_int16_t yy_def[313] =
    {   0,
      307,    1,  308,  308,  307,  307,  307,  307,  307,  309,
      310,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  307,  307,  307,  307,  309,
      307,  309,  310,  307,  310,  307,  307,  307,  307,  307,
      312,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  312,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,

      311,  311,  311,  311,  311,  311,  311,  309,  310,  307,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  312,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  309,  310,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  312,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,

      311,  311,  311,  311,  311,  311,  311,  309,  310,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  312,  307,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  309,  310,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  312,  307,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  309,  310,  311,  311,  311,  312,  307,  311,
      311,  311,  309,  309,  310,  310,  311,  311,  312,  307,
      311,  311,  309,  310,  311,  311,  312,  307,  307,  309,
      309,  310,  307,  310,  311,  311,  312,  311,  311,  312,

      311,  311,  311,  311,  311,  311,    0,  307,  307,  307,
      307,  307
    } ;

static const flex_int16_t yy_nxt[1253] =
    {   0,
        6,    7,    8,    7,    9,   10,   11,   12,   13,   14,
       15,   16,   17,   18,   19,   20,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
       34,   35,   36,   37,   38,   39,   35,   35,   40,   41,
       42,   43,   44,   45,   35,   35,   35,   46,   47,   35,
       25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   35,   35,   40,   41,   42,
       43,   44,   45,   35,   35,   51,   61,   56,   54,   57,
       57,   58,   59,   61,   61,   52,   52,   55,   55,   61,
       61,   61,   61,   61,   61,   61,   61,   68,  190,   66,

       54,   72,   63,   62,   69,   73,  240,   64,   61,   61,
       65,   70,   61,   61,   71,   61,   61,  226,   74,   67,
      110,  110,   75,   54,   61,   61,   68,  190,   66,   76,
       72,   63,   77,   69,   73,   78,   64,  107,   79,   65,
       70,   61,   61,   71,   61,   61,  226,   74,   67,   51,
       80,   75,   61,   61,   81,   61,   85,  139,   76,   54,
       82,   77,   61,   61,   78,   83,  107,   79,   88,   86,
       61,   61,   84,   61,   61,   87,   89,   61,   61,   80,
       61,   61,   51,   81,  252,   61,   61,   61,   61,   82,
       90,  100,  253,   94,   83,  101,   91,   88,   86,   92,

       51,   84,   51,   93,   87,   89,  102,  268,  103,  239,
      108,  108,   56,  252,   57,   57,   60,   61,   61,   90,
      100,  253,   94,  104,  101,   91,   49,  105,   92,   54,
      307,  106,   93,   61,   61,  102,  268,  103,  109,  109,
       61,   61,  307,   95,   61,   61,   96,   61,   61,  111,
       61,   61,  104,   61,   61,  112,  105,  307,   97,   98,
      106,  307,  113,   99,  269,  114,   61,   61,   61,   61,
       61,   61,   95,  279,  116,   96,   61,   61,  111,   54,
       61,   61,  307,  115,  112,  275,  120,   97,   98,   61,
       61,  113,   99,  269,  114,  121,   61,   61,  117,  307,

       61,   61,  279,  116,  118,  307,  119,   61,   61,  124,
       61,   61,  115,  122,  125,  120,   61,   61,   61,   61,
      123,  126,   61,   61,  121,   61,   61,  117,   61,   61,
      127,  110,  110,  118,  131,  119,   61,   61,  124,  128,
       61,   61,  122,  125,  307,  129,   61,   61,  130,  123,
      126,   61,   61,  132,   61,   61,  140,  141,  280,  127,
      138,   61,   61,  131,  287,   51,   61,   61,  128,   61,
       61,  145,   61,   61,  129,  162,  162,  130,   61,   61,
      288,  146,  132,   61,   61,  140,  141,  280,  143,  138,
      142,  144,  133,  287,  134,  147,  307,   61,   61,  307,

      145,  297,  135,   61,   61,   61,   61,  136,  137,  288,
      146,  159,   61,   61,  148,   61,   61,  143,  307,  142,
      144,  133,  149,  134,  147,  150,   61,   61,   61,   61,
      297,  135,  151,  152,  307,  154,  136,  137,   61,   61,
      159,   61,   61,  148,  307,  153,  307,   61,   61,   61,
       61,  149,   61,   61,  150,  156,  157,  307,   61,   61,
      307,  151,  152,   54,  154,  307,  158,  155,  160,   61,
       61,  307,  163,  163,  153,   61,   61,   61,   61,  161,
       61,   61,   61,   61,  156,  157,   61,   61,   61,   61,
      165,   61,   61,   51,  164,  158,  155,  160,   61,   61,

      273,   61,   61,   61,   61,  168,  167,  170,  161,  166,
       61,   61,  300,  171,   61,   61,  307,  169,  307,  165,
      172,  307,  173,  164,   61,   61,   61,   61,   61,   61,
      307,   61,   61,  307,  168,  167,  170,  178,  166,   61,
       61,  300,  171,  177,  307,  174,  169,   61,   61,  172,
      307,  173,  175,  176,   61,   61,  307,  179,  307,   61,
       61,  307,   61,   61,  307,  180,  178,   61,   61,  307,
       61,   61,  177,  182,  174,   61,   61,  184,   61,   61,
      181,  175,  176,  183,  185,  186,  179,  307,  187,  307,
       61,   61,   61,   61,  180,   61,   61,  307,   61,   61,

       61,   61,  182,   61,   61,  191,  184,  192,  307,  181,
      188,  189,  183,  185,  186,   61,   61,  187,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
      194,  307,  196,  307,  191,  193,  192,   61,   61,  188,
      189,  195,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,  199,   61,   61,  307,  197,   61,   61,  194,
      198,  196,  307,  200,  193,   61,   61,   61,   61,  307,
      195,  203,  202,  201,   61,   61,   51,   61,   61,  204,
      307,  199,  205,  307,   54,  197,  208,  208,  307,  198,
       61,   61,  200,  209,  209,  206,  210,  207,   61,   61,

      203,  202,  201,   61,   61,   61,   61,  307,  204,   61,
       61,  205,   61,   61,   61,   61,  307,  211,   61,   61,
       61,   61,   61,   61,  206,  210,  207,  307,  212,  307,
      213,   61,   61,   61,   61,   61,   61,  214,   61,   61,
      307,  217,  307,  215,   61,   61,  211,   61,   61,  307,
      219,  307,   61,   61,   61,   61,  216,  212,  307,  213,
      307,   61,   61,  218,   61,   61,  214,   61,   61,  307,
      217,  307,  215,  220,   61,   61,   61,   61,  227,  219,
      221,   61,   61,  307,  223,  216,   61,   61,   61,   61,
       61,   61,  218,  222,   61,   61,  307,  224,  307,  225,

      228,  307,  220,  307,   61,   61,  307,   61,   61,  221,
       61,   61,  307,  223,  230,   61,   61,  307,  231,   61,
       61,  307,  222,   61,   61,  232,  224,  229,  225,  228,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
      233,   61,   61,  230,   61,   61,  307,  231,  236,   61,
       61,   61,   61,  307,  232,  307,  229,   61,   61,  238,
      234,  235,   61,   61,  237,   61,   61,   61,   61,  233,
       61,   61,  242,   61,   61,   61,   61,  236,   61,   61,
      243,  307,  241,  244,  307,   61,   61,  307,  238,  234,
      235,  245,  246,  237,   61,   61,   61,   61,   61,   61,

      307,  242,  307,   61,   61,  307,   61,   61,  248,  243,
      247,  241,  244,  249,   61,   61,   61,   61,   61,   61,
      245,  246,   61,   61,  307,  254,   61,   61,  255,   61,
       61,   61,   61,  307,   61,   61,  307,  248,  307,  247,
      250,  251,  249,  257,  259,   61,   61,   61,   61,   61,
       61,  256,   51,  258,  254,  260,   54,  255,   61,   61,
       61,   61,  263,  263,  307,  264,  264,   61,   61,  307,
      251,  261,  257,  259,   61,   61,   61,   61,   61,   61,
      256,  262,  258,  307,  260,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,  307,   61,   61,

      261,  265,   61,   61,  266,   61,   61,   61,   61,  307,
      262,   61,   61,  271,  267,  270,  307,  272,   61,   61,
       61,   61,   61,   61,   61,   61,   54,   51,   61,   61,
       61,   61,  275,  266,  273,  276,  276,  274,  274,  277,
       61,   61,  271,  267,  270,   51,  272,   61,   61,   61,
       61,   61,   61,   61,   61,  283,  283,  281,   61,   61,
       54,   61,   61,  278,  307,  282,  307,  285,  277,  284,
      284,   61,   61,  289,  290,   61,   61,  307,  286,  292,
      293,  289,  290,  291,  291,  307,  281,  292,  293,  294,
      294,  307,  278,  307,  282,  307,  285,   61,   61,  295,

       61,   61,  307,   61,   61,  307,  296,  286,   61,   61,
       61,   61,   61,   61,  301,   61,   61,  307,  302,   61,
       61,   61,   61,   61,   61,  298,  307,  305,  295,  299,
      307,  303,  307,  306,  307,  296,   61,   61,  307,  307,
      304,  307,  307,  301,  307,  307,  307,  302,  307,  307,
      307,  307,  307,  307,  298,  307,  305,  307,  299,  307,
      303,  307,  306,  307,  307,  307,  307,  307,  307,  304,
       48,   48,   50,   50,   53,   53,    5,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,

      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307
    } ;

static const flex_int16_t yy_chk[1253] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,   10,  312,   20,   11,   20,
       20,   22,   22,   25,   25,   10,   10,   11,   11,   26,
       26,   27,   27,   29,   29,   28,   28,   27,  139,   26,

      209,   28,   25,  311,   27,   28,  209,   25,   35,   35,
       25,   27,   30,   30,   27,   31,   31,  190,   28,   26,
       56,   56,   29,  292,   45,   45,   27,  139,   26,   30,
       28,   25,   30,   27,   28,   30,   25,   45,   31,   25,
       27,   33,   33,   27,   32,   32,  190,   28,   26,  290,
       32,   29,   34,   34,   32,   36,   36,   85,   30,   53,
       33,   30,   37,   37,   30,   33,   45,   31,   37,   36,
       38,   38,   34,   40,   40,   36,   37,   62,   62,   32,
       39,   39,   50,   32,  226,   42,   42,   43,   43,   33,
       38,   42,  227,   40,   33,   42,   38,   37,   36,   39,

       52,   34,  208,   39,   36,   37,   43,  252,   43,  208,
       52,   52,   57,  226,   57,   57,   24,   44,   44,   38,
       42,  227,   40,   44,   42,   38,    9,   44,   39,   55,
        5,   44,   39,   41,   41,   43,  252,   43,   55,   55,
       63,   63,    0,   41,   67,   67,   41,   64,   64,   63,
       65,   65,   44,   66,   66,   64,   44,    0,   41,   41,
       44,    0,   65,   41,  253,   66,   68,   68,   69,   69,
       72,   72,   41,  268,   69,   41,   71,   71,   63,  276,
       70,   70,    0,   68,   64,  276,   71,   41,   41,   74,
       74,   65,   41,  253,   66,   72,   73,   73,   70,    0,

       75,   75,  268,   69,   70,    0,   70,   80,   80,   74,
       76,   76,   68,   73,   75,   71,   77,   77,   83,   83,
       73,   75,   92,   92,   72,   78,   78,   70,   79,   79,
       76,  110,  110,   70,   80,   70,   81,   81,   74,   77,
       86,   86,   73,   75,    0,   78,   84,   84,   79,   73,
       75,   87,   87,   81,   91,   91,   86,   87,  269,   76,
       84,   88,   88,   80,  279,  108,   90,   90,   77,   89,
       89,   91,   93,   93,   78,  108,  108,   79,   94,   94,
      280,   93,   81,   82,   82,   86,   87,  269,   89,   84,
       88,   90,   82,  279,   82,   94,    0,   95,   95,    0,

       91,  287,   82,  105,  105,   96,   96,   82,   82,  280,
       93,  105,   97,   97,   95,   98,   98,   89,    0,   88,
       90,   82,   95,   82,   94,   96,   99,   99,  100,  100,
      287,   82,   97,   98,    0,  100,   82,   82,  101,  101,
      105,  102,  102,   95,    0,   99,    0,  103,  103,  104,
      104,   95,  111,  111,   96,  102,  103,    0,  106,  106,
        0,   97,   98,  109,  100,    0,  104,  101,  106,  107,
      107,    0,  109,  109,   99,  112,  112,  113,  113,  107,
      114,  114,  115,  115,  102,  103,  116,  116,  117,  117,
      115,  118,  118,  274,  114,  104,  101,  106,  119,  119,

      274,  120,  120,  121,  121,  118,  117,  120,  107,  116,
      122,  122,  297,  121,  123,  123,    0,  119,    0,  115,
      122,    0,  123,  114,  124,  124,  126,  126,  125,  125,
        0,  127,  127,    0,  118,  117,  120,  127,  116,  128,
      128,  297,  121,  126,    0,  124,  119,  129,  129,  122,
        0,  123,  125,  125,  130,  130,    0,  128,    0,  131,
      131,    0,  132,  132,    0,  129,  127,  133,  133,    0,
      134,  134,  126,  131,  124,  135,  135,  133,  136,  136,
      130,  125,  125,  132,  134,  135,  128,    0,  136,    0,
      137,  137,  138,  138,  129,  140,  140,    0,  141,  141,

      142,  142,  131,  143,  143,  140,  133,  141,    0,  130,
      137,  138,  132,  134,  135,  144,  144,  136,  145,  145,
      146,  146,  148,  148,  147,  147,  149,  149,  150,  150,
      146,    0,  148,    0,  140,  145,  141,  151,  151,  137,
      138,  147,  152,  152,  153,  153,  154,  154,  155,  155,
      156,  156,  153,  158,  158,    0,  150,  159,  159,  146,
      151,  148,    0,  154,  145,  157,  157,  160,  160,    0,
      147,  157,  156,  155,  161,  161,  162,  164,  164,  158,
        0,  153,  159,    0,  163,  150,  162,  162,    0,  151,
      165,  165,  154,  163,  163,  160,  164,  161,  166,  166,

      157,  156,  155,  167,  167,  169,  169,    0,  158,  168,
      168,  159,  170,  170,  171,  171,    0,  167,  172,  172,
      173,  173,  174,  174,  160,  164,  161,    0,  168,    0,
      169,  175,  175,  176,  176,  177,  177,  170,  178,  178,
        0,  177,    0,  172,  179,  179,  167,  180,  180,    0,
      179,    0,  181,  181,  183,  183,  175,  168,    0,  169,
        0,  182,  182,  178,  184,  184,  170,  185,  185,    0,
      177,    0,  172,  181,  186,  186,  187,  187,  192,  179,
      182,  188,  188,    0,  185,  175,  189,  189,  191,  191,
      192,  192,  178,  184,  193,  193,    0,  186,    0,  187,

      193,    0,  181,    0,  194,  194,    0,  195,  195,  182,
      196,  196,    0,  185,  195,  197,  197,    0,  196,  198,
      198,    0,  184,  199,  199,  198,  186,  194,  187,  193,
      200,  200,  201,  201,  202,  202,  203,  203,  204,  204,
      200,  206,  206,  195,  205,  205,    0,  196,  204,  207,
      207,  210,  210,    0,  198,    0,  194,  211,  211,  207,
      202,  203,  212,  212,  205,  213,  213,  216,  216,  200,
      214,  214,  212,  215,  215,  218,  218,  204,  217,  217,
      214,    0,  211,  215,    0,  219,  219,    0,  207,  202,
      203,  216,  217,  205,  220,  220,  221,  221,  222,  222,

        0,  212,    0,  223,  223,    0,  224,  224,  221,  214,
      219,  211,  215,  223,  229,  229,  225,  225,  228,  228,
      216,  217,  230,  230,    0,  228,  231,  231,  230,  233,
      233,  232,  232,    0,  234,  234,    0,  221,    0,  219,
      224,  225,  223,  232,  234,  235,  235,  236,  236,  238,
      238,  231,  239,  233,  228,  235,  240,  230,  237,  237,
      241,  241,  239,  239,    0,  240,  240,  242,  242,    0,
      225,  236,  232,  234,  243,  243,  244,  244,  245,  245,
      231,  237,  233,    0,  235,  246,  246,  247,  247,  248,
      248,  249,  249,  250,  250,  251,  251,    0,  254,  254,

      236,  242,  256,  256,  246,  255,  255,  257,  257,    0,
      237,  258,  258,  255,  250,  254,    0,  257,  259,  259,
      260,  260,  261,  261,  262,  262,  264,  263,  266,  266,
      265,  265,  264,  246,  263,  264,  264,  263,  263,  265,
      267,  267,  255,  250,  254,  273,  257,  270,  270,  271,
      271,  272,  272,  277,  277,  273,  273,  270,  278,  278,
      275,  281,  281,  267,    0,  271,    0,  277,  265,  275,
      275,  282,  282,  283,  283,  285,  285,    0,  278,  284,
      284,  291,  291,  283,  283,    0,  270,  294,  294,  284,
      284,    0,  267,    0,  271,    0,  277,  286,  286,  285,

      295,  295,    0,  296,  296,    0,  286,  278,  298,  298,
      299,  299,  301,  301,  298,  302,  302,    0,  299,  303,
      303,  304,  304,  305,  305,  295,    0,  303,  285,  296,
        0,  301,    0,  305,    0,  286,  306,  306,    0,    0,
      302,    0,    0,  298,    0,    0,    0,  299,    0,    0,
        0,    0,    0,    0,  295,    0,  303,    0,  296,    0,
      301,    0,  305,    0,    0,    0,    0,    0,    0,  302,
      308,  308,  309,  309,  310,  310,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,

      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "lex_sql.l"

#line 28 "lex_sql.l"
#include<string.h>
#include<stdio.h>

/**
 * flex 代码包含三个部分，使用 %% 分隔
 * 第一个部分的代码是C代码，flex会原样复制到目标文件中
 * 第二个部分是规则部分，使用正则表达式定义一系列规则
 * 第三个部分还是C代码，flex 会复制此段代码
 */

#include "sql/parser/parse_defs.h"
#include "common/log/log.h"
#include "yacc_sql.hpp"

#ifndef register
#define register 
#endif // register

extern int atoi();
extern double atof();

#define RETURN_TOKEN(token) LOG_DEBUG("%s", #token);return token
#line 874 "lex_sql.cpp"
/* Prevent the need for linking with -lfl */
#define YY_NO_INPUT 1
/* 不区分大小写 */

/* 规则匹配的优先级：*/
/* 1. 匹配的规则长的优先 */
/* 2. 写在最前面的优先 */
/* yylval 就可以认为是 yacc 中 %union 定义的结构体(union 结构) */
#line 883 "lex_sql.cpp"

#define INITIAL 0
#define STR 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    int yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    YYSTYPE * yylval_r;

    YYLTYPE * yylloc_r;

    }; /* end struct yyguts_t */

static int yy_init_globals ( yyscan_t yyscanner );

    /* This must go here because YYSTYPE and YYLTYPE are included
     * from bison output in section 1.*/
    #    define yylval yyg->yylval_r
    
    #    define yylloc yyg->yylloc_r
    
int yylex_init (yyscan_t* scanner);

int yylex_init_extra ( YY_EXTRA_TYPE user_defined, yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( yyscan_t yyscanner );

int yyget_debug ( yyscan_t yyscanner );

void yyset_debug ( int debug_flag , yyscan_t yyscanner );

YY_EXTRA_TYPE yyget_extra ( yyscan_t yyscanner );

void yyset_extra ( YY_EXTRA_TYPE user_defined , yyscan_t yyscanner );

FILE *yyget_in ( yyscan_t yyscanner );

void yyset_in  ( FILE * _in_str , yyscan_t yyscanner );

FILE *yyget_out ( yyscan_t yyscanner );

void yyset_out  ( FILE * _out_str , yyscan_t yyscanner );

			int yyget_leng ( yyscan_t yyscanner );

char *yyget_text ( yyscan_t yyscanner );

int yyget_lineno ( yyscan_t yyscanner );

void yyset_lineno ( int _line_number , yyscan_t yyscanner );

int yyget_column  ( yyscan_t yyscanner );

void yyset_column ( int _column_no , yyscan_t yyscanner );

YYSTYPE * yyget_lval ( yyscan_t yyscanner );

void yyset_lval ( YYSTYPE * yylval_param , yyscan_t yyscanner );

       YYLTYPE *yyget_lloc ( yyscan_t yyscanner );
    
        void yyset_lloc ( YYLTYPE * yylloc_param , yyscan_t yyscanner );
    
/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( yyscan_t yyscanner );
#else
extern int yywrap ( yyscan_t yyscanner );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int , yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * , yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( yyscan_t yyscanner );
#else
static int input ( yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex \
               (YYSTYPE * yylval_param, YYLTYPE * yylloc_param , yyscan_t yyscanner);

#define YY_DECL int yylex \
               (YYSTYPE * yylval_param, YYLTYPE * yylloc_param , yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yylval = yylval_param;

    yylloc = yylloc_param;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
		}

		yy_load_buffer_state( yyscanner );
		}

	{
#line 75 "lex_sql.l"


#line 1169 "lex_sql.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 308 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1177 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 77 "lex_sql.l"
// ignore whitespace
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 78 "lex_sql.l"
;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 80 "lex_sql.l"
yylval->number=atoi(yytext); RETURN_TOKEN(NUMBER);
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 81 "lex_sql.l"
yylval->floats=(float)(atof(yytext)); RETURN_TOKEN(FLOAT);
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 83 "lex_sql.l"
RETURN_TOKEN(SEMICOLON);
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 84 "lex_sql.l"
RETURN_TOKEN(DOT);
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 85 "lex_sql.l"
RETURN_TOKEN(EXIT);
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 86 "lex_sql.l"
RETURN_TOKEN(HELP);
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 87 "lex_sql.l"
RETURN_TOKEN(DESC);
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 88 "lex_sql.l"
RETURN_TOKEN(CREATE);
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 89 "lex_sql.l"
RETURN_TOKEN(DROP);
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 90 "lex_sql.l"
RETURN_TOKEN(TABLE);
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 91 "lex_sql.l"
RETURN_TOKEN(TABLES);
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 92 "lex_sql.l"
RETURN_TOKEN(INDEX);
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 93 "lex_sql.l"
RETURN_TOKEN(VIEW);
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 94 "lex_sql.l"
RETURN_TOKEN(ON);
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 95 "lex_sql.l"
RETURN_TOKEN(SHOW);
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 96 "lex_sql.l"
RETURN_TOKEN(SYNC);
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 97 "lex_sql.l"
RETURN_TOKEN(SELECT);
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 98 "lex_sql.l"
RETURN_TOKEN(CALC);
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 99 "lex_sql.l"
RETURN_TOKEN(FROM);
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 100 "lex_sql.l"
RETURN_TOKEN(WHERE);
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 101 "lex_sql.l"
RETURN_TOKEN(AND);
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 102 "lex_sql.l"
RETURN_TOKEN(OR);
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 103 "lex_sql.l"
RETURN_TOKEN(INSERT);
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 104 "lex_sql.l"
RETURN_TOKEN(INTO);
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 105 "lex_sql.l"
RETURN_TOKEN(VALUES);
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 106 "lex_sql.l"
RETURN_TOKEN(DELETE);
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 107 "lex_sql.l"
RETURN_TOKEN(UPDATE);
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 108 "lex_sql.l"
RETURN_TOKEN(SET);
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 109 "lex_sql.l"
RETURN_TOKEN(TRX_BEGIN);
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 110 "lex_sql.l"
RETURN_TOKEN(TRX_COMMIT);
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 111 "lex_sql.l"
RETURN_TOKEN(TRX_ROLLBACK);
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 112 "lex_sql.l"
RETURN_TOKEN(L2_DISTANCE_T);
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 113 "lex_sql.l"
RETURN_TOKEN(COSINE_DISTANCE_T);
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 114 "lex_sql.l"
RETURN_TOKEN(INNER_PRODUCT_T);
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 115 "lex_sql.l"
RETURN_TOKEN(INT_T);
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 116 "lex_sql.l"
RETURN_TOKEN(DATE_T);
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 117 "lex_sql.l"
RETURN_TOKEN(TEXT_T);
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 118 "lex_sql.l"
RETURN_TOKEN(VECTOR_T);
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 119 "lex_sql.l"
RETURN_TOKEN(STRING_T);
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 120 "lex_sql.l"
RETURN_TOKEN(FLOAT_T);
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 121 "lex_sql.l"
RETURN_TOKEN(LOAD_DATA);
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 122 "lex_sql.l"
RETURN_TOKEN(INFILE);
	YY_BREAK
case 45:
#line 124 "lex_sql.l"
case 46:
#line 125 "lex_sql.l"
case 47:
#line 126 "lex_sql.l"
case 48:
#line 127 "lex_sql.l"
case 49:
YY_RULE_SETUP
#line 127 "lex_sql.l"
yylval->string=strdup(yytext); RETURN_TOKEN(AGGR);
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 128 "lex_sql.l"
RETURN_TOKEN(EXPLAIN);
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 129 "lex_sql.l"
RETURN_TOKEN(ASC);
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 130 "lex_sql.l"
RETURN_TOKEN(ORDER);
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 131 "lex_sql.l"
RETURN_TOKEN(GROUP);
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 132 "lex_sql.l"
RETURN_TOKEN(BY);
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 133 "lex_sql.l"
RETURN_TOKEN(AS);
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 134 "lex_sql.l"
RETURN_TOKEN(STORAGE);
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 135 "lex_sql.l"
RETURN_TOKEN(FORMAT);
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 136 "lex_sql.l"
RETURN_TOKEN(NOT);
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 137 "lex_sql.l"
RETURN_TOKEN(LIKE);
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 138 "lex_sql.l"
RETURN_TOKEN(UNIQUE);
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 139 "lex_sql.l"
RETURN_TOKEN(INNER);
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 140 "lex_sql.l"
RETURN_TOKEN(JOIN);
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 141 "lex_sql.l"
RETURN_TOKEN(NULL_T);
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 142 "lex_sql.l"
RETURN_TOKEN(NULL_T);
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 143 "lex_sql.l"
RETURN_TOKEN(IS);
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 144 "lex_sql.l"
RETURN_TOKEN(IN);
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 145 "lex_sql.l"
RETURN_TOKEN(EXISTS);
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 146 "lex_sql.l"
RETURN_TOKEN(HAVING);
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 147 "lex_sql.l"
yylval->string=strdup(yytext); RETURN_TOKEN(ID);
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 148 "lex_sql.l"
RETURN_TOKEN(LBRACE);
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 149 "lex_sql.l"
RETURN_TOKEN(RBRACE);
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 150 "lex_sql.l"
RETURN_TOKEN(LBRACK);
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 151 "lex_sql.l"
RETURN_TOKEN(RBRACK);
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 153 "lex_sql.l"
RETURN_TOKEN(COMMA);
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 154 "lex_sql.l"
RETURN_TOKEN(EQ);
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 155 "lex_sql.l"
RETURN_TOKEN(LE);
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 156 "lex_sql.l"
RETURN_TOKEN(NE);
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 157 "lex_sql.l"
RETURN_TOKEN(NE);
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 158 "lex_sql.l"
RETURN_TOKEN(LT);
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 159 "lex_sql.l"
RETURN_TOKEN(GE);
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 160 "lex_sql.l"
RETURN_TOKEN(GT);
	YY_BREAK
case 82:
#line 163 "lex_sql.l"
case 83:
#line 164 "lex_sql.l"
case 84:
#line 165 "lex_sql.l"
case 85:
YY_RULE_SETUP
#line 165 "lex_sql.l"
{ return yytext[0]; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 166 "lex_sql.l"
yylval->string=strdup(yytext); RETURN_TOKEN(DATE_STR);
	YY_BREAK
case 87:
/* rule 87 can match eol */
YY_RULE_SETUP
#line 167 "lex_sql.l"
yylval->string = strdup(yytext); RETURN_TOKEN(SSS);
	YY_BREAK
case 88:
/* rule 88 can match eol */
YY_RULE_SETUP
#line 168 "lex_sql.l"
yylval->string = strdup(yytext); RETURN_TOKEN(SSS);
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 170 "lex_sql.l"
LOG_DEBUG("Unknown character [%c]",yytext[0]); return yytext[0];
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 171 "lex_sql.l"
ECHO;
	YY_BREAK
#line 1658 "lex_sql.cpp"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STR):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( yywrap( yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = yyg->yytext_ptr;
	int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  , yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size , yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 308 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	char *yy_cp = yyg->yy_c_buf_p;

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 308 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 307);

	(void)yyg;
	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr);
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin , yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( yyscanner ) )
						return 0;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file , yyscanner);
	yy_load_buffer_state( yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void yy_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file , yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * @param yyscanner The scanner object.
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf , yyscanner );

	yyfree( (void *) b , yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_flush_buffer( b , yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack(yyscanner);

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void yypop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER , yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (yyscan_t yyscanner)
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b , yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr , yyscan_t yyscanner)
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) , yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n , yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n , yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE yyget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int yyget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int yyget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
int yyget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *yyget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void yyset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param _line_number line number
 * @param yyscanner The scanner object.
 */
void yyset_lineno (int  _line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_lineno called with no buffer" );
    
    yylineno = _line_number;
}

/** Set the current column.
 * @param _column_no column number
 * @param yyscanner The scanner object.
 */
void yyset_column (int  _column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_column called with no buffer" );
    
    yycolumn = _column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = _in_str ;
}

void yyset_out (FILE *  _out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = _out_str ;
}

int yyget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void yyset_debug (int  _bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = _bdebug ;
}

/* Accessor methods for yylval and yylloc */

YYSTYPE * yyget_lval  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylval;
}

void yyset_lval (YYSTYPE *  yylval_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylval = yylval_param;
}

YYLTYPE *yyget_lloc  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylloc;
}
    
void yyset_lloc (YYLTYPE *  yylloc_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylloc = yylloc_param;
}
    
/* User-visible API */

/* yylex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */
int yylex_init(yyscan_t* ptr_yy_globals)
{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* yylex_init_extra has the same functionality as yylex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to yyalloc in
 * the yyextra field.
 */
int yylex_init_extra( YY_EXTRA_TYPE yy_user_defined, yyscan_t* ptr_yy_globals )
{
    struct yyguts_t dummy_yyguts;

    yyset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    yyset_extra (yy_user_defined, *ptr_yy_globals);

    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = NULL;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = NULL;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER , yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	yyfree(yyg->yy_buffer_stack , yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        yyfree( yyg->yy_start_stack , yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    yyfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s , yyscan_t yyscanner)
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 171 "lex_sql.l"


void scan_string(const char *str, yyscan_t scanner) {
  yy_switch_to_buffer(yy_scan_string(str, scanner), scanner);
}

